# Generated by Django 3.0 on 2020-02-02 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200202_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dish_list',
        ),
        migrations.AddField(
            model_name='dish',
            name='order_number',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='dish_list', to='orders.Order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
