# Generated by Django 3.0 on 2020-02-02 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200202_2046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name_plural': 'Dishes'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Menu item', 'verbose_name_plural': 'Menu items'},
        ),
    ]
