# Generated by Django 3.0 on 2020-02-03 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200202_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='kind',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='menu',
            name='size',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='menu',
            name='toppings_amount',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
