# Generated by Django 3.0 on 2020-02-04 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200203_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='toppings_amount',
        ),
    ]
