# Generated by Django 3.0.3 on 2020-02-07 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200206_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemname',
            name='kind_id',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='size_id',
        ),
        migrations.AddField(
            model_name='itemname',
            name='kind',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='name_list', to='orders.ItemKind'),
        ),
        migrations.AddField(
            model_name='menu',
            name='kind',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='item_list', to='orders.ItemKind'),
        ),
        migrations.AddField(
            model_name='menu',
            name='name',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='item_list', to='orders.ItemName'),
        ),
        migrations.AddField(
            model_name='menu',
            name='size',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.DeleteModel(
            name='ItemSize',
        ),
    ]
