# Generated by Django 3.0.3 on 2020-02-07 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200207_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemname',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='name',
        ),
        migrations.AddField(
            model_name='itemname',
            name='parent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='name_list', to='orders.ItemKind'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='item_list', to='orders.ItemName'),
        ),
    ]
