# Generated by Django 3.0.3 on 2020-02-07 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20200207_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='size',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name_parent',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='item_list', to='orders.ItemName'),
        ),
        migrations.AlterField(
            model_name='itemname',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_list', to='orders.ItemKind'),
        ),
        migrations.CreateModel(
            name='ItemSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(default='', max_length=64)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_list', to='orders.ItemName')),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='size_parent',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='item_list', to='orders.ItemSize'),
        ),
    ]
